### ISSUE TITLE
EKS Cluster Managed Service Account Token Secret Refreshes Every Second

### ISSUE THREAD

**Issue by zhujian7** [open-cluster-management-io/managed-serviceaccount#119]
**Describe the bug**
When an EKS cluster is imported, its managed service account keeps refreshing its token secret.
**To Reproduce**
1. Import an EKS cluster to the ocm hub and enable the managedserviceaccount addon
2. create a managedserviceaccount whose spec.rotation.validity great than 1 day:
```
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: test-msa
  namespace: eks
spec:
  rotation:
    enabled: true
    validity: 168h0m0s
```
3. Check if its token secret ref is refreshed without stop  

**Expected behavior**

**Environment ie: OCM version, managed serviceaccount addon version, Kubernetes version and provider:**

managed serviceaccount version: 58e960782819524b70ba63b55287a42c5c34639f

**Additional context**
